### ISSUE TITLE
Directories inside the created zip file

### ISSUE THREAD

**Issue by alexcorvi** [alexcorvi/php-zip#1]
When adding a directory that has it's own sub-directories, the zip file created contains all the files but no directories.

This is not a bug, it's rather a limitation that I'll fix as soon as I have some time.

**Comment by alexcorvi** [comment]
### Suggested fix: a smart detection

It will guess the directory based on the present files to be added.

Say we have an array of files to be added like this

`1/2/3/4/a.png` <= file added as single file
`1/2/3/4/b.png` <= file added as single file
`1/2/3/4/c.png` <= file added as single file
`1/2/3/7/dir/x.png` <= file added as a directory
`1/2/3/7/dir/y.png` <= file added as a directory
`1/2/3/7/dir/dir2/z.png` <= file added as a directory

It will find the common directories (in the above case `1/2/3/`) and strip it out then add the directories inside of which the files respectively.

**Comment by cryocreations** [comment]
I cannot add directories, and from the comment above it doesn't look like it will retain the directory structure. All files I add lose the first character of the filename.

I'm going to use another plugin until you update it, shame, would have been perfect otherwise.

**Comment by alexcorvi** [comment]
Fixed
