### ISSUE TITLE
Return Value Issue

### ISSUE THREAD

**Issue by baljindersingh88** [alexcorvi/php-zip#4]
HI,
Zip is created but getting boolean(true)
Any help will be appreciated.
Thanks
BJ

**Comment by ThomasPerraudin** [comment]
I confirm. This return is annoying. Maybe a new option $verbose could be added ?

**Comment by ThomasPerraudin** [comment]
I confirm. This return is annoying. Maybe a new option $verbose could be added ?

I can see a var_dump in Zip.php line 267.

**Comment by alexcorvi** [comment]
Please check latest release.
